version: 2.1

executors:
  node:
    docker:
      - image: circleci/node

commands:
  setup:
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-v3-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v3-{{ .Branch }}-
            - yarn-packages-v3-
      - run: yarn install --immutable --cache-folder ~/.cache/yarn
  cleanup:
    steps:
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-packages-v3-{{ .Branch }}-{{ checksum "yarn.lock" }}

jobs:
  test:
    executor: node
    steps:
      - setup
      - run: yarn test
      - cleanup
